# fly.toml app configuration file generated for todolist-with-next-spring-backend on 2024-12-10T10:19:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todolist-with-next-spring-backend'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[http_service.concurrency]
  type = "connections"
  hard_limit = 550
  soft_limit = 500

[[services.ports]]
  handlers = ["http"]
  port = 8080