CREATE TABLE IF NOT EXISTS users (
  user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  hashed_password VARCHAR(60) NOT NULL,
  thumbnail_path VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tasks (
  task_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  task_name VARCHAR(100) NOT NULL,
  is_complete BOOLEAN NOT NULL DEFAULT FALSE,
  due_date DATETIME,
  FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
